let CONST_endpoint_url = "endpoint_url"
let CONST_url_whitelist = "url_whitelist"
let CONST_api_key = "api_key"
let CONST_whitelist_on = "whitelist_on"
let CONST_extension_notification_title = "URL Plugin"